In [ ]:
#for period of one second we detect if the eeg record is indicative of a seizure

In [39]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv('data.csv')

In [41]:
data.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

In [42]:
data.describe()

X1            X2            X3            X4            X5  \
count  11500.000000  11500.000000  11500.000000  11500.000000  11500.000000   
mean     -11.581391    -10.911565    -10.187130     -9.143043     -8.009739   
std      165.626284    166.059609    163.524317    161.269041    160.998007   
min    -1839.000000  -1838.000000  -1835.000000  -1845.000000  -1791.000000   
25%      -54.000000    -55.000000    -54.000000    -54.000000    -54.000000   
50%       -8.000000     -8.000000     -7.000000     -8.000000     -8.000000   
75%       34.000000     35.000000     36.000000     36.000000     35.000000   
max     1726.000000   1713.000000   1697.000000   1612.000000   1518.000000   

                 X6            X7           X8           X9           X10  \
count  11500.000000  11500.000000  11500.00000  11500.00000  11500.000000   
mean      -7.003478     -6.502087     -6.68713     -6.55800     -6.168435   
std      161.328725    161.467837    162.11912    162.03336    160.436352   
min    -1757.000000  -1832.000000  -1778.00000  -1840.00000  -1867.000000   
25%      -54.000000    -54.000000    -55.00000    -55.00000    -54.000000   
50%       -8.000000     -8.000000     -8.00000     -7.00000     -7.000000   
75%       36.000000     35.000000     36.00000     36.00000     35.250000   
max     1816.000000   2047.000000   2047.00000   2047.00000   2047.000000   

           ...               X170          X171          X172          X173  \
count      ...       11500.000000  11500.000000  11500.000000  11500.000000   
mean       ...         -10.145739    -11.630348    -12.943478    -13.668870   
std        ...         164.652883    166.149790    168.554058    168.556486   
min        ...       -1867.000000  -1865.000000  -1642.000000  -1723.000000   
25%        ...         -55.000000    -56.000000    -56.000000    -56.000000   
50%        ...          -9.000000    -10.000000    -10.000000    -10.000000   
75%        ...          34.000000     34.000000     33.000000     33.000000   
max        ...        1777.000000   1472.000000   1319.000000   1436.000000   

               X174          X175          X176          X177          X178  \
count  11500.000000  11500.000000  11500.000000  11500.000000  11500.000000   
mean     -13.363304    -13.045043    -12.705130    -12.426000    -12.195652   
std      167.257290    164.241019    162.895832    162.886311    164.852015   
min    -1866.000000  -1863.000000  -1781.000000  -1727.000000  -1829.000000   
25%      -55.000000    -56.000000    -55.000000    -55.000000    -55.000000   
50%      -10.000000     -9.000000     -9.000000     -9.000000     -9.000000   
75%       34.000000     34.000000     34.000000     34.000000     34.000000   
max     1733.000000   1958.000000   2047.000000   2047.000000   1915.000000   

                  y  
count  11500.000000  
mean       3.000000  
std        1.414275  
min        1.000000  
25%        2.000000  
50%        3.000000  
75%        4.000000  
max        5.000000  

[8 rows x 179 columns]

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Columns: 180 entries, Unnamed: 0 to y
dtypes: int64(179), object(1)
memory usage: 15.8+ MB


In [44]:
data.isnull().values.any()

False

In [45]:
data['y'].value_counts()

5    2300
4    2300
3    2300
2    2300
1    2300
Name: y, dtype: int64

### So to convert a multi classification problem to binary classification:
#### The classes are:
5 - eyes open, means when they were recording the EEG signal of the brain the patient had their eyes open

4 - eyes closed, means when they were recording the EEG signal the patient had their eyes closed

3 - Yes they identify where the region of the tumor was in the brain and recording the EEG activity from the healthy brain area

2 - They recorded the EEG from the area where the tumor was located

1 - Recording of seizure activity 

#### All subjects falling in classes 2, 3, 4, and 5 are subjects who did not have epileptic seizure. Only subjects in class 1 have epileptic seizure. So now we will have two classes 1 (epileptic seizure), 0 (no epileptic seizure) : 2300, 9200 records respectively, which introduces some skew

In [46]:
data = data.iloc[:,1:]

In [47]:
data['y'] = data['y'].replace([5,4,3,2],0)

In [48]:
#data.iloc[:,:-1]
#data.iloc[:,-1]

In [49]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)

In [11]:
# normalizing:
standard_scaler = preprocessing.StandardScaler()
X_train = pd.DataFrame(standard_scaler.fit_transform(X_train))
X_test = pd.DataFrame(standard_scaler.fit_transform(X_test))

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,roc_auc_score,confusion_matrix,average_precision_score
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.93495652173913046

In [14]:
roc_auc = roc_auc_score(y_test,y_pred)
roc_auc

0.89304701088459615

In [15]:
avg_precision = average_precision_score(y_test,y_pred)
avg_precision

0.84958539912991993

In [16]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[2224,   88],
       [  99,  464]])

In [17]:

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

predictions = [round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
roc_auc = roc_auc_score(y_test,y_pred)
print("ROC-AUC: %.2f%%" % (accuracy * 100.0))
avg_precision = average_precision_score(y_test,y_pred)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
cm = confusion_matrix(y_test,predictions)
print("Confusion Matrix : ")
print(cm)

Accuracy: 96.14%
ROC-AUC: 96.14%
Average Precision : 91.11%
Confusion Matrix : 
[[2255   57]
 [  54  509]]


In [19]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
roc_auc = roc_auc_score(y_test,predictions)
print("ROC-AUC: %.2f%%" % (roc_auc * 100.0))
avg_precision = average_precision_score(y_test,predictions)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
cm = confusion_matrix(y_test,predictions)
print("Confusion Matrix : ")
print(cm)

Accuracy: 96.83%
ROC-AUC: 93.46%
Average Precision : 92.92%
Confusion Matrix : 
[[2289   23]
 [  68  495]]


In [26]:
len(X_train.columns)

178

In [36]:
import tensorflow
from keras.models import Sequential
from keras.layers import Dense
import numpy
model = Sequential()
model.add(Dense(200,input_dim=178,activation='relu'))
model.add(Dense(180,activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Using TensorFlow backend.


ImportError: No module named 'tensorflow.python'

In [64]:
model.fit(X_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
8625/8625 [==============================] - 9s 1ms/step - loss: 0.2098 - acc: 0.9399
Epoch 2/10
8625/8625 [==============================] - 6s 676us/step - loss: 0.1094 - acc: 0.9688
Epoch 3/10
8625/8625 [==============================] - 8s 952us/step - loss: 0.0701 - acc: 0.9782
Epoch 4/10
8625/8625 [==============================] - 5s 634us/step - loss: 0.0710 - acc: 0.9781
Epoch 5/10
8625/8625 [==============================] - 8s 964us/step - loss: 0.0488 - acc: 0.9839
Epoch 6/10
8625/8625 [==============================] - 6s 667us/step - loss: 0.0475 - acc: 0.9842
Epoch 7/10
8625/8625 [==============================] - 9s 997us/step - loss: 0.0448 - acc: 0.9853
Epoch 8/10
8625/8625 [==============================] - 6s 642us/step - loss: 0.0346 - acc: 0.9884
Epoch 9/10
8625/8625 [==============================] - 8s 950us/step - loss: 0.0328 - acc: 0.9886
Epoch 10/10
8625/8625 [==============================] - 6s 752us/step - loss: 0.0300 - acc: 0.9908


In [65]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

2875/2875 [==============================] - 1s 235us/step

acc: 97.57%


In [66]:
pred = model.predict(X_test)
pred = [round(x[0]) for x in pred]
roc_auc = roc_auc_score(y_test,pred)
print("ROC-AUC: %.2f%%" % (roc_auc * 100.0))
avg_precision = average_precision_score(y_test,pred)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
cm = confusion_matrix(y_test,pred)
print("Confusion Matrix : ")
print(cm)

ROC-AUC: 95.46%
Average Precision : 89.34%
Confusion Matrix : 
[[2287   25]
 [  45  518]]


In [72]:
X_train.shape
x_train = X_train.values.reshape(X_train.shape[0],X_train.shape[1],1)

array([[[-0.30853946],
        [-0.26532072],
        [-0.25208695],
        ...,
        [-0.32744531],
        [-0.36886774],
        [-0.4950382 ]],

       [[-0.40309855],
        [-0.46100651],
        [-0.53037082],
        ...,
        [ 0.04960057],
        [ 0.00585526],
        [-0.01268024]],

       [[ 0.1110665 ],
        [ 0.07861189],
        [ 0.05644516],
        ...,
        [ 0.06814381],
        [ 0.01199826],
        [-0.05542082]],

       ...,

       [[ 0.17607588],
        [ 0.1853496 ],
        [ 0.21978569],
        ...,
        [-0.19764263],
        [-0.18457774],
        [-0.14700777]],

       [[ 1.75403069],
        [ 1.73897621],
        [ 1.94393572],
        ...,
        [-0.06165887],
        [-0.98931073],
        [-1.80778456]],

       [[-0.62767639],
        [ 0.39289514],
        [ 1.7079994 ],
        ...,
        [-3.34999341],
        [-3.01035771],
        [-2.21687296]]])

In [76]:
from keras.layers import Conv1D,LSTM,MaxPool1D,Dropout
CNN1D = Sequential()
CNN1D.add(Conv1D(10,10,activation='elu',input_shape=(178,1)))
CNN1D.add(MaxPool1D(4,1))
CNN1D.add(Dropout(0.2))
CNN1D.add(LSTM(128, return_sequences=True))
CNN1D.add(LSTM(64)) 
CNN1D.add(Dense(1,activation='sigmoid'))
CNN1D.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [82]:
CNN1D.fit(x_train, y_train, epochs=5, batch_size=100)

Epoch 1/5
8625/8625 [==============================] - 160s 19ms/step - loss: 0.0737 - acc: 0.9769
Epoch 2/5
8625/8625 [==============================] - 161s 19ms/step - loss: 0.0621 - acc: 0.9794
Epoch 3/5
8625/8625 [==============================] - 158s 18ms/step - loss: 0.0665 - acc: 0.9775
Epoch 4/5
8625/8625 [==============================] - 159s 18ms/step - loss: 0.0574 - acc: 0.9805
Epoch 5/5
8625/8625 [==============================] - 73s 8ms/step - loss: 0.0595 - acc: 0.9789


In [84]:
x_test = X_test.values.reshape(X_test.shape[0],X_test.shape[1],1)
scores = CNN1D.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (CNN1D.metrics_names[1], scores[1]*100))

2875/2875 [==============================] - 18s 6ms/step

acc: 98.19%


In [86]:
pred = CNN1D.predict(x_test)
pred = [round(x[0]) for x in pred]
roc_auc = roc_auc_score(y_test,pred)
print("ROC-AUC: %.2f%%" % (roc_auc * 100.0))
avg_precision = average_precision_score(y_test,pred)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
cm = confusion_matrix(y_test,pred)
print("Confusion Matrix : ")
print(cm)

ROC-AUC: 97.33%
Average Precision : 91.83%
Confusion Matrix : 
[[2283   29]
 [  23  540]]


In [57]:
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
#SVM WITH RBF KERNEL
svm_clf = SVC(C=4,gamma=1.3)
svm_clf = svm_clf.fit(X_train, y_train)
predict = svm_clf.predict(X_test)


In [58]:
#pred = [round(x[0]) for x in predict]
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
roc_auc = roc_auc_score(y_test,predict)
print("ROC-AUC: %.2f%%" % (roc_auc * 100.0))
avg_precision = average_precision_score(y_test,predict)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
#print(accuracy_score(y_test, predict))
#print(classification_report(y_test, predict))
#accuracies.append(accuracy_score(y_test, predict))
#f_scores.append(f1_score(y_test, predict,average = "macro"))
cm = confusion_matrix(y_test,predict)
print("Confusion Matrix : ")
print(cm)

Accuracy: 96.83%
ROC-AUC: 50.00%
Average Precision : 59.79%
Confusion Matrix : 
[[2312    0]
 [ 563    0]]


In [1]:
linear_svm_clf = LinearSVC(C=0.1)
linear_svm_clf = linear_svm_clf.fit(X_train, y_train)
predict = linear_svm_clf.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
roc_auc = roc_auc_score(y_test,predict)
print("ROC-AUC: %.2f%%" % (roc_auc * 100.0))
avg_precision = average_precision_score(y_test,predict)
print("Average Precision : %.2f%%" % (avg_precision*100.0))
cm = confusion_matrix(y_test,predict)
print("Confusion Matrix : ")
print(cm)
print()
print()
print(classification_report(y_test, predict))

NameError: name 'LinearSVC' is not defined